name: EAS Build and Test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Install, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci || npm i

      - name: Run tests
        run: npm test

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: "latest"
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        run: eas build --platform android --non-interactive --no-wait
