name: Build Expo App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: EAS Login
        run: eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Expo App
        run: eas build --platform android --non-interactive
